<a href="https://colab.research.google.com/github/swati-malik/ann/blob/master/ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
data = pd.read_csv('Churn_Modelling.csv')

In [0]:
data

RowNumber  CustomerId  ... EstimatedSalary  Exited
0             1    15634602  ...       101348.88       1
1             2    15647311  ...       112542.58       0
2             3    15619304  ...       113931.57       1
3             4    15701354  ...        93826.63       0
4             5    15737888  ...        79084.10       0
5             6    15574012  ...       149756.71       1
6             7    15592531  ...        10062.80       0
7             8    15656148  ...       119346.88       1
8             9    15792365  ...        74940.50       0
9            10    15592389  ...        71725.73       0
10           11    15767821  ...        80181.12       0
11           12    15737173  ...        76390.01       0
12           13    15632264  ...        26260.98       0
13           14    15691483  ...       190857.79       0
14           15    15600882  ...        65951.65       0
15           16    15643966  ...        64327.26       0
16           17    15737452  ...         5097.67       1
17           18    15788218  ...        14406.41       0
18           19    15661507  ...       158684.81       0
19           20    15568982  ...        54724.03       0
20           21    15577657  ...       170886.17       0
21           22    15597945  ...       138555.46       0
22           23    15699309  ...       118913.53       1
23           24    15725737  ...         8487.75       0
24           25    15625047  ...       187616.16       0
25           26    15738191  ...       124508.29       0
26           27    15736816  ...       170041.95       0
27           28    15700772  ...        38433.35       0
28           29    15728693  ...       100187.43       0
29           30    15656300  ...        53483.21       0
...         ...         ...  ...             ...     ...
9970       9971    15587133  ...       119377.36       0
9971       9972    15721377  ...       166472.81       0
9972       9973    15747927  ...       171552.02       0
9973       9974    15806455  ...       157474.10       0
9974       9975    15695474  ...        13549.24       0
9975       9976    15666295  ...       196526.55       1
9976       9977    15656062  ...        84419.78       0
9977       9978    15579969  ...        24991.92       0
9978       9979    15703563  ...       191608.97       0
9979       9980    15692664  ...         2988.28       0
9980       9981    15719276  ...        99595.67       0
9981       9982    15672754  ...        53445.17       1
9982       9983    15768163  ...       115146.40       1
9983       9984    15656710  ...       151325.24       0
9984       9985    15696175  ...        51695.41       0
9985       9986    15586914  ...        96833.00       0
9986       9987    15581736  ...        34047.54       0
9987       9988    15588839  ...         1914.41       0
9988       9989    15589329  ...        49337.84       0
9989       9990    15605622  ...       179436.60       0
9990       9991    15798964  ...        53667.08       0
9991       9992    15769959  ...        69384.71       1
9992       9993    15657105  ...       195192.40       0
9993       9994    15569266  ...        29179.52       0
9994       9995    15719294  ...       167773.55       0
9995       9996    15606229  ...        96270.64       0
9996       9997    15569892  ...       101699.77       0
9997       9998    15584532  ...        42085.58       1
9998       9999    15682355  ...        92888.52       1
9999      10000    15628319  ...        38190.78       0

[10000 rows x 14 columns]

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
x = data.iloc[:,3:13].values

In [0]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [0]:
y = data.iloc[:,13].values

In [0]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [0]:

from sklearn.model_selection import train_test_split

In [0]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder


In [0]:
le1 = LabelEncoder()
le2 = LabelEncoder()

In [0]:
x[:, 1]= le1.fit_transform(x[:, 1])

In [0]:
x[:,2] = le2.fit_transform(x[:,2])

In [0]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
#onehotencoding
onehotencoder = OneHotEncoder(categorical_features=[1])



In [0]:
x= onehotencoder.fit_transform(x).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [0]:
x = pd.DataFrame(x)

In [0]:
x

0    1    2      3    4   ...         7    8    9    10         11
0     1.0  0.0  0.0  619.0  0.0  ...       0.00  1.0  1.0  1.0  101348.88
1     0.0  0.0  1.0  608.0  0.0  ...   83807.86  1.0  0.0  1.0  112542.58
2     1.0  0.0  0.0  502.0  0.0  ...  159660.80  3.0  1.0  0.0  113931.57
3     1.0  0.0  0.0  699.0  0.0  ...       0.00  2.0  0.0  0.0   93826.63
4     0.0  0.0  1.0  850.0  0.0  ...  125510.82  1.0  1.0  1.0   79084.10
5     0.0  0.0  1.0  645.0  1.0  ...  113755.78  2.0  1.0  0.0  149756.71
6     1.0  0.0  0.0  822.0  1.0  ...       0.00  2.0  1.0  1.0   10062.80
7     0.0  1.0  0.0  376.0  0.0  ...  115046.74  4.0  1.0  0.0  119346.88
8     1.0  0.0  0.0  501.0  1.0  ...  142051.07  2.0  0.0  1.0   74940.50
9     1.0  0.0  0.0  684.0  1.0  ...  134603.88  1.0  1.0  1.0   71725.73
10    1.0  0.0  0.0  528.0  1.0  ...  102016.72  2.0  0.0  0.0   80181.12
11    0.0  0.0  1.0  497.0  1.0  ...       0.00  2.0  1.0  0.0   76390.01
12    1.0  0.0  0.0  476.0  0.0  ...       0.00  2.0  1.0  0.0   26260.98
13    1.0  0.0  0.0  549.0  0.0  ...       0.00  2.0  0.0  0.0  190857.79
14    0.0  0.0  1.0  635.0  0.0  ...       0.00  2.0  1.0  1.0   65951.65
15    0.0  1.0  0.0  616.0  1.0  ...  143129.41  2.0  0.0  1.0   64327.26
16    0.0  1.0  0.0  653.0  1.0  ...  132602.88  1.0  1.0  0.0    5097.67
17    0.0  0.0  1.0  549.0  0.0  ...       0.00  2.0  1.0  1.0   14406.41
18    0.0  0.0  1.0  587.0  1.0  ...       0.00  1.0  0.0  0.0  158684.81
19    1.0  0.0  0.0  726.0  0.0  ...       0.00  2.0  1.0  1.0   54724.03
20    1.0  0.0  0.0  732.0  1.0  ...       0.00  2.0  1.0  1.0  170886.17
21    0.0  0.0  1.0  636.0  0.0  ...       0.00  2.0  1.0  0.0  138555.46
22    0.0  0.0  1.0  510.0  0.0  ...       0.00  1.0  1.0  0.0  118913.53
23    1.0  0.0  0.0  669.0  1.0  ...       0.00  2.0  0.0  1.0    8487.75
24    1.0  0.0  0.0  846.0  0.0  ...       0.00  1.0  1.0  1.0  187616.16
25    1.0  0.0  0.0  577.0  1.0  ...       0.00  2.0  0.0  1.0  124508.29
26    0.0  1.0  0.0  756.0  1.0  ...  136815.64  1.0  1.0  1.0  170041.95
27    1.0  0.0  0.0  571.0  1.0  ...       0.00  2.0  0.0  0.0   38433.35
28    0.0  1.0  0.0  574.0  0.0  ...  141349.43  1.0  1.0  1.0  100187.43
29    1.0  0.0  0.0  411.0  1.0  ...   59697.17  2.0  1.0  1.0   53483.21
...   ...  ...  ...    ...  ...  ...        ...  ...  ...  ...        ...
9970  1.0  0.0  0.0  518.0  1.0  ...  151027.05  2.0  1.0  0.0  119377.36
9971  1.0  0.0  0.0  833.0  0.0  ...  144751.81  1.0  0.0  0.0  166472.81
9972  1.0  0.0  0.0  758.0  1.0  ...  155739.76  1.0  1.0  0.0  171552.02
9973  1.0  0.0  0.0  611.0  1.0  ...       0.00  2.0  1.0  1.0  157474.10
9974  1.0  0.0  0.0  583.0  1.0  ...  122531.86  1.0  1.0  0.0   13549.24
9975  0.0  1.0  0.0  610.0  1.0  ...  113957.01  2.0  1.0  0.0  196526.55
9976  1.0  0.0  0.0  637.0  0.0  ...  103377.81  1.0  1.0  0.0   84419.78
9977  1.0  0.0  0.0  683.0  0.0  ...       0.00  2.0  1.0  1.0   24991.92
9978  1.0  0.0  0.0  774.0  1.0  ...   93017.47  2.0  1.0  0.0  191608.97
9979  1.0  0.0  0.0  677.0  0.0  ...   90022.85  1.0  0.0  1.0    2988.28
9980  0.0  0.0  1.0  741.0  1.0  ...   74371.49  1.0  0.0  0.0   99595.67
9981  0.0  1.0  0.0  498.0  1.0  ...  152039.70  1.0  1.0  1.0   53445.17
9982  0.0  1.0  0.0  655.0  0.0  ...  137145.12  1.0  1.0  0.0  115146.40
9983  1.0  0.0  0.0  613.0  1.0  ...       0.00  1.0  0.0  0.0  151325.24
9984  0.0  1.0  0.0  602.0  1.0  ...   90602.42  2.0  1.0  1.0   51695.41
9985  1.0  0.0  0.0  659.0  1.0  ...  123841.49  2.0  1.0  0.0   96833.00
9986  0.0  1.0  0.0  673.0  1.0  ...  183579.54  2.0  0.0  1.0   34047.54
9987  0.0  0.0  1.0  606.0  1.0  ...  180307.73  2.0  1.0  1.0    1914.41
9988  1.0  0.0  0.0  775.0  1.0  ...       0.00  2.0  1.0  0.0   49337.84
9989  0.0  0.0  1.0  841.0  1.0  ...       0.00  2.0  1.0  1.0  179436.60
9990  0.0  1.0  0.0  714.0  1.0  ...   35016.60  1.0  1.0  0.0   53667.08
9991  1.0  0.0  0.0  597.0  0.0  ...   88381.21  1.0  1.0  0.0   69384.71
9992  0.0  

In [0]:
x = x.iloc[:,1:]

In [0]:
x

1    2      3    4     5     6          7    8    9    10         11
0     0.0  0.0  619.0  0.0  42.0   2.0       0.00  1.0  1.0  1.0  101348.88
1     0.0  1.0  608.0  0.0  41.0   1.0   83807.86  1.0  0.0  1.0  112542.58
2     0.0  0.0  502.0  0.0  42.0   8.0  159660.80  3.0  1.0  0.0  113931.57
3     0.0  0.0  699.0  0.0  39.0   1.0       0.00  2.0  0.0  0.0   93826.63
4     0.0  1.0  850.0  0.0  43.0   2.0  125510.82  1.0  1.0  1.0   79084.10
5     0.0  1.0  645.0  1.0  44.0   8.0  113755.78  2.0  1.0  0.0  149756.71
6     0.0  0.0  822.0  1.0  50.0   7.0       0.00  2.0  1.0  1.0   10062.80
7     1.0  0.0  376.0  0.0  29.0   4.0  115046.74  4.0  1.0  0.0  119346.88
8     0.0  0.0  501.0  1.0  44.0   4.0  142051.07  2.0  0.0  1.0   74940.50
9     0.0  0.0  684.0  1.0  27.0   2.0  134603.88  1.0  1.0  1.0   71725.73
10    0.0  0.0  528.0  1.0  31.0   6.0  102016.72  2.0  0.0  0.0   80181.12
11    0.0  1.0  497.0  1.0  24.0   3.0       0.00  2.0  1.0  0.0   76390.01
12    0.0  0.0  476.0  0.0  34.0  10.0       0.00  2.0  1.0  0.0   26260.98
13    0.0  0.0  549.0  0.0  25.0   5.0       0.00  2.0  0.0  0.0  190857.79
14    0.0  1.0  635.0  0.0  35.0   7.0       0.00  2.0  1.0  1.0   65951.65
15    1.0  0.0  616.0  1.0  45.0   3.0  143129.41  2.0  0.0  1.0   64327.26
16    1.0  0.0  653.0  1.0  58.0   1.0  132602.88  1.0  1.0  0.0    5097.67
17    0.0  1.0  549.0  0.0  24.0   9.0       0.00  2.0  1.0  1.0   14406.41
18    0.0  1.0  587.0  1.0  45.0   6.0       0.00  1.0  0.0  0.0  158684.81
19    0.0  0.0  726.0  0.0  24.0   6.0       0.00  2.0  1.0  1.0   54724.03
20    0.0  0.0  732.0  1.0  41.0   8.0       0.00  2.0  1.0  1.0  170886.17
21    0.0  1.0  636.0  0.0  32.0   8.0       0.00  2.0  1.0  0.0  138555.46
22    0.0  1.0  510.0  0.0  38.0   4.0       0.00  1.0  1.0  0.0  118913.53
23    0.0  0.0  669.0  1.0  46.0   3.0       0.00  2.0  0.0  1.0    8487.75
24    0.0  0.0  846.0  0.0  38.0   5.0       0.00  1.0  1.0  1.0  187616.16
25    0.0  0.0  577.0  1.0  25.0   3.0       0.00  2.0  0.0  1.0  124508.29
26    1.0  0.0  756.0  1.0  36.0   2.0  136815.64  1.0  1.0  1.0  170041.95
27    0.0  0.0  571.0  1.0  44.0   9.0       0.00  2.0  0.0  0.0   38433.35
28    1.0  0.0  574.0  0.0  43.0   3.0  141349.43  1.0  1.0  1.0  100187.43
29    0.0  0.0  411.0  1.0  29.0   0.0   59697.17  2.0  1.0  1.0   53483.21
...   ...  ...    ...  ...   ...   ...        ...  ...  ...  ...        ...
9970  0.0  0.0  518.0  1.0  42.0   7.0  151027.05  2.0  1.0  0.0  119377.36
9971  0.0  0.0  833.0  0.0  34.0   3.0  144751.81  1.0  0.0  0.0  166472.81
9972  0.0  0.0  758.0  1.0  26.0   4.0  155739.76  1.0  1.0  0.0  171552.02
9973  0.0  0.0  611.0  1.0  27.0   7.0       0.00  2.0  1.0  1.0  157474.10
9974  0.0  0.0  583.0  1.0  33.0   7.0  122531.86  1.0  1.0  0.0   13549.24
9975  1.0  0.0  610.0  1.0  50.0   1.0  113957.01  2.0  1.0  0.0  196526.55
9976  0.0  0.0  637.0  0.0  33.0   7.0  103377.81  1.0  1.0  0.0   84419.78
9977  0.0  0.0  683.0  0.0  32.0   9.0       0.00  2.0  1.0  1.0   24991.92
9978  0.0  0.0  774.0  1.0  40.0   9.0   93017.47  2.0  1.0  0.0  191608.97
9979  0.0  0.0  677.0  0.0  58.0   1.0   90022.85  1.0  0.0  1.0    2988.28
9980  0.0  1.0  741.0  1.0  35.0   6.0   74371.49  1.0  0.0  0.0   99595.67
9981  1.0  0.0  498.0  1.0  42.0   3.0  152039.70  1.0  1.0  1.0   53445.17
9982  1.0  0.0  655.0  0.0  46.0   7.0  137145.12  1.0  1.0  0.0  115146.40
9983  0.0  0.0  613.0  1.0  40.0   4.0       0.00  1.0  0.0  0.0  151325.24
9984  1.0  0.0  602.0  1.0  35.0   7.0   90602.42  2.0  1.0  1.0   51695.41
9985  0.0  0.0  659.0  1.0  36.0   6.0  123841.49  2.0  1.0  0.0   96833.00
9986  1.0  0.0  673.0  1.0  47.0   1.0  183579.54  2.0  0.0  1.0   34047.54
9987  0.0  1.0  606.0  1.0  30.0   8.0  180307.73  2.0  1.0  1.0    1914.41
9988  0.0  0.0  775.0  1.0  30.0   4.0       0.00  2.0  1.0  0.0   49337.84
9989  0.0  1.0  841.0  1.0  28.0   4.0       0.00  2.0  1.0  1.0  179436.60
9990  1.0  0.0  714.0  1.0  33.0   3.0   35016.60  1.0 

In [0]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

feature scaling


In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:

sc = StandardScaler()

In [0]:
x_train = sc.fit_transform(x_train)

In [0]:
x_test = sc.fit_transform(x_test)

In [0]:
import keras

Using TensorFlow backend.


In [0]:
from keras.models  import Sequential

In [0]:
from keras.layers import Dense

In [0]:
classifier = Sequential()

**for hidden layer **


-output_dim argument signifies the no. of nodes in the hidden layer and on experimental basis it can be calculated by taking the average of input and output nodes.

-init argument is used to initialize the weights.

-activation function for hidden layer is usually taken as relu.

-activation fucnction for output layer is taken 'sigmoid' if we have binary output and 'softmax ' if the output contains more than two categories.

In [0]:
#second hidden layer
classifier.add(Dense(output_dim=6,init = 'uniform',activation='relu',input_dim = 11))

Instructions for updating:
Colocations handled automatically by placer.


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
#second hidden layer
classifier.add(Dense(output_dim=6,init = 'uniform',activation='relu'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
#output layer
classifier.add(Dense(output_dim=1,init = 'uniform',activation='sigmoid'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [0]:
classifier.fit(x_train,y_train,batch_size = 10,epochs = 100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.4880 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.4284 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 91us/step - loss: 0.4233 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.4196 - acc: 0.8104
Epoch 5/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.4168 - acc: 0.8249
Epoch 6/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.4152 - acc: 0.8281
Epoch 7/100
8000/8000 [==============================] - 1s 98us/step - loss: 0.4119 - acc: 0.8324
Epoch 8/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.4090 - acc: 0.8334
Epoch 9/100
8000/8000 [==============================] - 1s 91us/step - loss: 0.4062 - acc: 0.8340
Epoch 10/100
8000/8000 [==============================] - 1s

In [0]:
y_pred = classifier.predict(x_test)

In [0]:
y_pred = y_pred>0.5

In [0]:
from sklearn.metrics import confusion_matrix

In [0]:
cm = confusion_matrix(y_test,y_pred)

In [0]:
cm

array([[1549,   46],
       [ 229,  176]])

In [0]:
(1549+176)/2000

0.8625

In [0]:
y_pred = pd.DataFrame(y_pred)

In [0]:
y_pred

0
0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14     True
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
...     ...
1970  False
1971  False
1972  False
1973  False
1974  False
1975  False
1976  False
1977  False
1978  False
1979  False
1980  False
1981   True
1982  False
1983  False
1984  False
1985  False
1986  False
1987  False
1988  False
1989  False
1990  False
1991  False
1992  False
1993  False
1994  False
1995  False
1996  False
1997  False
1998  False
1999  False

[2000 rows x 1 columns]

predict if the coustomer with the following will leave the bank or stay in the bank:

geography- france

credit score:600

gender:male

age:40

tenure:3

balance:60000

no.of products:2

has credit card:yes

is active member:yes

estimated slary:50000


we need to apply standard scaler since our classifier was trained on diffrent scale so when we make a new prediction it has to be made on the same scale.

In [0]:
new_prediction = classifier.predict(sc.transform(np.array([[0,0,600,1,40,3,60000,2,1,1,50000]])))

In [0]:
new_prediction = new_prediction>0.5

In [0]:
new_prediction

array([[False]])

In [0]:
#so as per the given information the individual will not leave the bank 